# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R		 
sudo: required
cache: 
  - packages	
  - /usr/local
dist: trusty

r_github_packages:
  - jimhester/covr
    
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  ## saga and grass need to be installed from source and not using ubuntugis
  # install qgis and qgis-plugin-grass from 'ubuntugis'
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev qgis python-qgis qgis-plugin-grass
  ## compile SAGA 2.2.2 from source
  - cd && wget https://sourceforge.net/projects/saga-gis/files/SAGA%20-%202.2/SAGA%202.2.2/saga-2.2.2.tar.gz && tar xvzf saga-2.2.2.tar.gz && rm saga-2.2.2.tar.gz
  - sudo apt-get install libwxgtk3.0-dev libtiff5-dev libgdal-dev libproj-dev libjasper-dev libexpat1-dev wx-common libexpat1-dev libogdi3.2-dev unixodbc-dev
  - cd saga-2.2.2 && sudo autoreconf -i > /dev/null && ./configure > /dev/null && make > /dev/null && sudo make install > /dev/null && export SAGA_MLB=/usr/local/lib/saga && export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - cd /home/travis/build/jannes-m/RQGIS
  
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
    
after_success:
  - Rscript -e 'covr::codecov()'

# inspect log of failing tests
after_failure: "cat /home/travis/build/jannes-m/RQGIS/RQGIS.Rcheck/00check.log"





