# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
## See https://github.com/metacran/r-builder for details.
## settings from edzer/gstat

language: R		 
sudo: required
cache: packages	

env:
  global:
    - R_CHECK_ARGS = "--no-tests"
    
r_github_packages: 
  - hadley/devtools
  - jimhester/covr
    
before_install:
  - wget http://download.osgeo.org/gdal/2.1.1/gdal-2.1.1.tar.gz
  - tar zxf gdal-2.1.1.tar.gz
  - cd gdal-2.1.1
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar zxvf proj-4.9.3.tar.gz
  - cd proj-4.9.3
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd /home/travis/build/jannes-m/RQGIS

notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'covr::codecov()'





